# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=200)),
                ('coordinator', models.CharField(max_length=200)),
                ('coordinator_phone', models.CharField(max_length=20)),
                ('coordinator_email', models.EmailField(max_length=254)),
                ('recurring', models.BooleanField()),
                ('previous_subsidy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_subsidy_date', models.DateField()),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('uj_attendees', models.IntegerField()),
                ('other_attendees', models.IntegerField()),
                ('target_group_justification', models.TextField()),
                ('project_goals', models.TextField()),
                ('work_plan', models.TextField()),
                ('project_value', models.TextField()),
                ('support_visibility', models.TextField()),
                ('cooperating_organizations', models.TextField()),
                ('scope', models.CharField(choices=[('international', 'International'), ('nationwide', 'Nationwide'), ('environmental', 'Environmental'), ('university', 'University')], max_length=50)),
                ('programme', models.TextField()),
                ('overall_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requested_subsidy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('submitted', models.BooleanField()),
            ],
        ),
    ]
