# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='scope',
            field=models.CharField(choices=[('international', 'International'), ('nationwide', 'Nationwide'), ('environmental', 'Environmental'), ('university', 'University')], default='university', max_length=50),
        ),
    ]
