# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurum', '0003_auto_20170511_0709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('view_application', 'View application'), ('edit_application', 'Edit application'))},
        ),
    ]
