# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurum', '0006_auto_20170511_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cooperating_organizations',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='coordinator',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='coordinator_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='coordinator_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='faculty',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='other_attendees',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='overall_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='previous_subsidy',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='previous_subsidy_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='programme',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='project_goals',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='project_value',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='recurring',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='requested_subsidy',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='support_visibility',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='target_group_justification',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='uj_attendees',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='work_plan',
            field=models.TextField(null=True),
        ),
    ]
