# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurum', '0008_auto_20170511_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('submitted', 'Submitted')], default='new', max_length=20),
        ),
    ]
