# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 10:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesaurum', '0009_application_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('application', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='thesaurum.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_question', models.BooleanField(default=False)),
                ('second_question', models.BooleanField(default=False)),
                ('third_question', models.BooleanField(default=False)),
                ('fourth_question', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesaurum.Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
