# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesaurum', '0010_file_grading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('view_application', 'View application'), ('edit_application', 'Edit application'), ('grade_application', 'Can grade application'))},
        ),
        migrations.RemoveField(
            model_name='application',
            name='submitted',
        ),
        migrations.AddField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
