# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurum', '0013_grading_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grading',
            options={'permissions': (('view_grading', 'View grading'),)},
        ),
    ]
