# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurum', '0015_auto_20170515_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='vote',
            field=models.CharField(choices=[('in_favor', 'In favor'), ('abstain', 'Abstain'), ('against', 'Against')], default='abstain', max_length=10),
        ),
    ]
